USE [master]
GO

/****** Object:  Database [Lab2]    Script Date: 23.12.2018 16:50:23 ******/
CREATE DATABASE [Lab2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Lab2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Lab2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Lab2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Lab2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Lab2] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Lab2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Lab2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Lab2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Lab2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Lab2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Lab2] SET ARITHABORT OFF 
GO

ALTER DATABASE [Lab2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Lab2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Lab2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Lab2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Lab2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Lab2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Lab2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Lab2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Lab2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Lab2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Lab2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Lab2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Lab2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Lab2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Lab2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Lab2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Lab2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Lab2] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Lab2] SET  MULTI_USER 
GO

ALTER DATABASE [Lab2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Lab2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Lab2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Lab2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Lab2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Lab2] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Lab2] SET  READ_WRITE 
GO

USE [Lab2]
GO

/****** Object:  Table [dbo].[Banks]    Script Date: 23.12.2018 16:52:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Banks](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](50) NOT NULL,
	[city] [nvarchar](50) NULL,
	[phone_number] [nvarchar](50) NULL,
	[country_ID] [int] NULL,
 CONSTRAINT [PK_Banks] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Countries]    Script Date: 23.12.2018 16:53:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Countries](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](50) NOT NULL,
	[capital] [nvarchar](50) NOT NULL,
	[currency] [nchar](10) NOT NULL,
	[bank_ID] [int] NULL,
 CONSTRAINT [PK_Countries] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[CountryBank]    Script Date: 23.12.2018 16:53:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CountryBank](
	[country_ID] [int] NOT NULL,
	[bank_ID] [int] NOT NULL,
 CONSTRAINT [PK_CountryBank] PRIMARY KEY CLUSTERED 
(
	[country_ID] ASC,
	[bank_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CountryBank]  WITH CHECK ADD  CONSTRAINT [FK_CountryBank_Banks] FOREIGN KEY([bank_ID])
REFERENCES [dbo].[Banks] ([id])
GO

ALTER TABLE [dbo].[CountryBank] CHECK CONSTRAINT [FK_CountryBank_Banks]
GO

ALTER TABLE [dbo].[CountryBank]  WITH CHECK ADD  CONSTRAINT [FK_CountryBank_Countries] FOREIGN KEY([country_ID])
REFERENCES [dbo].[Countries] ([id])
GO

ALTER TABLE [dbo].[CountryBank] CHECK CONSTRAINT [FK_CountryBank_Countries]
GO